language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer self-update
  - composer global require "hirak/prestissimo:^0.3"
install:
  - composer install --no-interaction
script:
  - ./vendor/bin/phpcs src
  - ./vendor/bin/phpstan analyze src
  - ./vendor/bin/phpunit
cache:
  directories:
    - $HOME/.composer/cache
