version: 2.1
defaults: &defaults
  docker:
    - image: circleci/php:7.2-cli
      environment:
        BOX_VERSION: 3.6.0
  working_directory: ~/repo
aliases:
  - &composer-cache
      v4-composer-cache
commands:
  start-project:
    steps:
      - run: sudo apt-get update && sudo apt-get install -y libpng-dev libjpeg62-turbo-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd
      - checkout
      - restore_cache:
          keys:
            - *composer-cache
      - run: composer global require "hirak/prestissimo:^0.3"
      - run: composer install -n --prefer-dist
      - save_cache:
          key: *composer-cache
          paths:
            - ~/.composer/cache
  create-drupal-project:
    parameters:
      project:
        type: string
        default: 'drupal-composer/drupal-project:8.x-dev'
    steps:
      - run: composer create-project << parameters.project >> /tmp/drupal --no-interaction --no-dev --prefer-dist --ignore-platform-reqs
  local-require:
    steps:
      - run:
          name: Add as local
          command: |
            cd /tmp/drupal
            composer config repositories.phpstanDrupal '{"type": "path", "url": "~/repo", "options": { "symlink": false }}'
            composer require mglaman/phpstan-drupal *@dev
            cp ~/repo/tests/fixtures/config/drupal-phpstan.neon /tmp/drupal/phpstan.neon
            ./vendor/bin/phpstan --version
  global-require:
    steps:
      - run:
          name: Add PHPStan
          command: |
            composer global require phpstan/phpstan
      - run:
          name: Remove vendor directory
          command: |
            rm -rf vendor
      - run:
          name: Add project as a global dependency
          command: |
            composer global config repositories.phpstanDrupal '{"type": "path", "url": "~/repo", "options": { "symlink": false }}'
      - run:
          name: Add globally
          command: |
            composer global require mglaman/phpstan-drupal *@dev
      - run:
          name: Add Composer global path
          command: |
            echo 'export PATH="$HOME/.composer/vendor/bin:$PATH"' >> $BASH_ENV
            echo $BASH_ENV
      - run:
          name: Check drupal-check can be executed
          command: |
            phpstan --version
jobs:
  build:
    <<: *defaults
    steps:
      - start-project
      - run:
          name: CodeSniffer
          command: ./vendor/bin/phpcs src
      - run:
          name: PHPStan Analyze
          command: ./vendor/bin/phpstan analyze src
      - run:
          name: PHPUnit
          command: ./vendor/bin/phpunit
  test_drupal:
    <<: *defaults
    steps:
      - start-project
      - create-drupal-project:
          project: 'drupal/drupal:^8@alpha'
      - local-require
      - run:
          name: Run against a file
          command: |
            cd /tmp/drupal
            ./vendor/bin/phpstan analyze core/install.php
      - run:
          name: Run against a module
          command: |
            cd /tmp/drupal
            ./vendor/bin/phpstan analyze core/modules/dynamic_page_cache | grep -q "not found and could not be autoloaded." && false || true

workflows:
  version: 2
  tests:
    jobs:
      - build
      - test_drupal
